### ISSUE TITLE
Doesn't <Appwrite {...config}> expose secrets?

### ISSUE THREAD

**Issue by digitaldrreamer** [koodeau/metawrite#8]
Hey👋,
Just started using Appwrite recently. Nice project, by the way.
I might be wrong, but doesn't using the config in client side expose Appwrite secrets (like the project id)?
```svelte
<Appwrite {...config}>
```  
Would really appreciate a good response.
Thanks.

**Comment by koodeau** [comment]
@Codes-Wizard good question. This config is intended to be used on client side, similar to Firebase. Hers's some [documentation](https://appwrite.io/docs/getting-started-for-web#initSDK). If you want more security you can create an API key for server side usage inside your Appwrite console and use it inside `.server.ts/js` files in SvelteKit.

**Comment by digitaldrreamer** [comment]
> @Codes-Wizard good question. This config is intended to be used on client side, similar to Firebase. Hers's some [documentation](https://appwrite.io/docs/getting-started-for-web#initSDK). If you want more security you can create an API key for server side usage inside your Appwrite console and use it inside `.server.ts/js` files in SvelteKit. 

Ok. Thanks, by the way
